extend type Course {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Course", purpose: IMPLICIT_KEY_FIELD)
}
extend type ExpenseCategory {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ExpenseCategory", purpose: IMPLICIT_KEY_FIELD)
}
extend type Institution {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Institution", purpose: IMPLICIT_KEY_FIELD)
}
extend type PointsBalance {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PointsBalance", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PointsBalance`.`user`. It must match the value of `User`.`username`. See `@ref` for how to customize it.
  """
  userUsername: String! @fdc_generated(from: "PointsBalance.user", purpose: IMPLICIT_REF_FIELD)
}
extend type PointsTransaction {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PointsTransaction", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PointsTransaction`.`user`. It must match the value of `User`.`username`. See `@ref` for how to customize it.
  """
  userUsername: String! @fdc_generated(from: "PointsTransaction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Scholarship {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Scholarship", purpose: IMPLICIT_KEY_FIELD)
}
extend type ScholarshipApplication {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ScholarshipApplication", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ScholarshipApplication`.`scholarship`. It must match the value of `Scholarship`.`id`. See `@ref` for how to customize it.
  """
  scholarshipId: UUID! @fdc_generated(from: "ScholarshipApplication.scholarship", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ScholarshipApplication`.`user`. It must match the value of `User`.`username`. See `@ref` for how to customize it.
  """
  userUsername: String! @fdc_generated(from: "ScholarshipApplication.user", purpose: IMPLICIT_REF_FIELD)
}
extend type School {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "School", purpose: IMPLICIT_KEY_FIELD)
}
extend type Transaction {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Transaction", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`user`. It must match the value of `User`.`username`. See `@ref` for how to customize it.
  """
  userUsername: String! @fdc_generated(from: "Transaction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit foreign key field based on `User`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID @fdc_generated(from: "User.course", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `User`.`school`. It must match the value of `School`.`id`. See `@ref` for how to customize it.
  """
  schoolId: UUID @fdc_generated(from: "User.school", purpose: IMPLICIT_REF_FIELD)
}
