extend type CategoryBudget {
  """
  ✨ Implicit foreign key field based on `CategoryBudget`.`user`. It must match the value of `User`.`userId`. See `@ref` for how to customize it.
  """
  userUserId: String! @fdc_generated(from: "CategoryBudget.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `CategoryBudget`.`category`. It must match the value of `ExpenseCategory`.`id`. See `@ref` for how to customize it.
  """
  categoryId: UUID! @fdc_generated(from: "CategoryBudget.category", purpose: IMPLICIT_REF_FIELD)
}
extend type CountryContinent {
  """
  ✨ Implicit foreign key field based on `CountryContinent`.`country`. It must match the value of `Country`.`id`. See `@ref` for how to customize it.
  """
  countryId: Int! @fdc_generated(from: "CountryContinent.country", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `CountryContinent`.`continent`. It must match the value of `Continent`.`id`. See `@ref` for how to customize it.
  """
  continentId: Int! @fdc_generated(from: "CountryContinent.continent", purpose: IMPLICIT_REF_FIELD)
}
extend type Course {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Course", purpose: IMPLICIT_KEY_FIELD)
}
extend type ExpenseCategory {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ExpenseCategory", purpose: IMPLICIT_KEY_FIELD)
}
extend type Institution {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Institution", purpose: IMPLICIT_KEY_FIELD)
}
extend type PointsBalance {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PointsBalance", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PointsBalance`.`user`. It must match the value of `User`.`userId`. See `@ref` for how to customize it.
  """
  userUserId: String! @fdc_generated(from: "PointsBalance.user", purpose: IMPLICIT_REF_FIELD)
}
extend type PointsTransaction {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PointsTransaction", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PointsTransaction`.`user`. It must match the value of `User`.`userId`. See `@ref` for how to customize it.
  """
  userUserId: String! @fdc_generated(from: "PointsTransaction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Product {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Product", purpose: IMPLICIT_KEY_FIELD)
}
extend type RedeemedProduct {
  """
  ✨ Implicit foreign key field based on `RedeemedProduct`.`user`. It must match the value of `User`.`userId`. See `@ref` for how to customize it.
  """
  userUserId: String! @fdc_generated(from: "RedeemedProduct.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `RedeemedProduct`.`product`. It must match the value of `Product`.`id`. See `@ref` for how to customize it.
  """
  productId: UUID! @fdc_generated(from: "RedeemedProduct.product", purpose: IMPLICIT_REF_FIELD)
}
extend type Scholarship {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Scholarship", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Scholarship`.`continent`. It must match the value of `Continent`.`id`. See `@ref` for how to customize it.
  """
  continentId: Int @fdc_generated(from: "Scholarship.continent", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Scholarship`.`country`. It must match the value of `Country`.`id`. See `@ref` for how to customize it.
  """
  countryId: Int @fdc_generated(from: "Scholarship.country", purpose: IMPLICIT_REF_FIELD)
}
extend type ScholarshipApplication {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ScholarshipApplication", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ScholarshipApplication`.`scholarship`. It must match the value of `Scholarship`.`id`. See `@ref` for how to customize it.
  """
  scholarshipId: UUID! @fdc_generated(from: "ScholarshipApplication.scholarship", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ScholarshipApplication`.`user`. It must match the value of `User`.`userId`. See `@ref` for how to customize it.
  """
  userUserId: String! @fdc_generated(from: "ScholarshipApplication.user", purpose: IMPLICIT_REF_FIELD)
}
extend type ScholarshipCourse {
  """
  ✨ Implicit foreign key field based on `ScholarshipCourse`.`scholarship`. It must match the value of `Scholarship`.`id`. See `@ref` for how to customize it.
  """
  scholarshipId: UUID! @fdc_generated(from: "ScholarshipCourse.scholarship", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `ScholarshipCourse`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID! @fdc_generated(from: "ScholarshipCourse.course", purpose: IMPLICIT_REF_FIELD)
}
extend type Transaction {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Transaction", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`category`. It must match the value of `ExpenseCategory`.`id`. See `@ref` for how to customize it.
  """
  categoryId: UUID! @fdc_generated(from: "Transaction.category", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`user`. It must match the value of `User`.`userId`. See `@ref` for how to customize it.
  """
  userUserId: String! @fdc_generated(from: "Transaction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit foreign key field based on `User`.`country`. It must match the value of `Country`.`id`. See `@ref` for how to customize it.
  """
  countryId: Int @fdc_generated(from: "User.country", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `User`.`course`. It must match the value of `Course`.`id`. See `@ref` for how to customize it.
  """
  courseId: UUID @fdc_generated(from: "User.course", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `User`.`institution`. It must match the value of `Institution`.`id`. See `@ref` for how to customize it.
  """
  institutionId: UUID @fdc_generated(from: "User.institution", purpose: IMPLICIT_REF_FIELD)
}
