mutation SeedOnboardingData @transaction @auth(level: USER, insecureReason: "Seed data is for initialization.") {
  institution_insertMany(data: [
    { name: "University of Malta (UoM)" },
    { name: "Malta College of Arts, Science and Technology (MCAST)" },
    { name: "STC Higher Education" },
    { name: "Institute of Tourism Studies (ITS)" },
    { name: "St Martin's Institute of IT" },
    { name: "Global College Malta" },
    { name: "American University of Malta (AUM)" },
    { name: "London School of Commerce Malta" },
    { name: "Middlesex University Malta" },
    { name: "Pegaso International" },
    { name: "Other" }
  ])
  course_insertMany(data: [
    { name: "Computer Science" },
    { name: "Information Technology" },
    { name: "Software Engineering" },
    { name: "Data Science" },
    { name: "Artificial Intelligence" },
    { name: "Business Management" },
    { name: "Accounting" },
    { name: "Finance" },
    { name: "Mechanical Engineering" },
    { name: "Electrical Engineering" },
    { name: "Civil Engineering" },
    { name: "Medicine" },
    { name: "Nursing" },
    { name: "Health Sciences" },
    { name: "Arts" },
    { name: "Humanities" },
    { name: "Media Studies" },
    { name: "Communications" },
    { name: "Law" },
    { name: "Legal Studies" },
    { name: "Science" },
    { name: "Mathematics" },
    { name: "Education" },
    { name: "Teaching" },
    { name: "Architecture" },
    { name: "Design" },
    { name: "Psychology" },
    { name: "Sociology" },
    { name: "Hospitality" },
    { name: "Tourism" },
    { name: "Other" }
  ])
}
